Add options to let user choose which function to do in setup-deployment-server so that we can debug and reinstall deployment server easily instead of doing everything from scratch.
Change-Id: I55ca86b06022aa336725c9d899dda1f6f8793ad4
Signed-off-by: QingFeng Hao <haoqf@linux.vnet.ibm.com>

diff --git a/tools/deployer_for_linuxone/setup-deployment-server b/tools/deployer_for_linuxone/setup-deployment-server
--- a/tools/deployer_for_linuxone/setup-deployment-server
+++ b/tools/deployer_for_linuxone/setup-deployment-server
@@ -10,6 +10,7 @@ function usage {
 Usage: $0 [options]
 
 Options:
+    --install-all, -all                        Install all
     --repo-port, -r <repository_port>          Specify the port to be used by the local package repository server, default is 8000
     --pypi-port, -p <pypi_port>                Specify the port to be used by the local pypi server, default is 8080
     --docker-registry-port, -d <registry_port> Specify the port to be used by the local docker registry server, default is 5000
@@ -18,6 +19,12 @@ Options:
                                                If not specified, will try to automatically get the address using ifconfig and exclude
                                                the address 127.0.0.1 and 172.17.0.1(which is used by docker0).
                                                If two or more address are filtered, will abort.
+    --install-, -b <CE_base_dir>               Specify the base directory, default is /data
+    --install-docker, -k                       Install docker only and restart package repository server, pypi server and docker registry server
+    --setup-repo, -s                           Setup local repository and install pip only
+    --install-kolla-ansible, -t                Install kolla-ansible only
+    --config-kolla-ansible, -c                 Configure kolla-ansible only
+    --gen-script, -g                           Generate the openstack-ce-presetups.sh only
     --help, -h                                 Show this usage information
 EOF
 }
@@ -81,8 +88,8 @@ function get_bind_addr {
 }
 
 
-SHORT_OPTS="hr:p:b:d:a:"
-LONG_OPTS="help,repo-port:,pypi-port:,docker-registry-port:,base-dir:,bind-addr:"
+SHORT_OPTS="hr:p:b:d:a:k:s,t,c,g,all"
+LONG_OPTS="help,repo-port:,pypi-port:,docker-registry-port:,base-dir:,bind-addr:,install-all,install-docker,setup-repo,install-kolla-ansible,config-kolla-ansible,gen-script"
 ARGS=$(getopt -o "${SHORT_OPTS}" -l "${LONG_OPTS}" --name "$0" -- "$@") || { usage >&2; exit 2; }
 
 eval set -- "$ARGS"
@@ -92,8 +99,18 @@ PYPI_PORT=8080
 DOCKER_REGISTRY_PORT=5000
 CE_BASE="/data"
 BIND_ADDR=""
+INSTALL_DOCKER=0
+SETUP_REPO=0
+INSTALL_KOLLA_ANSIBLE=0
+CONFIG_KOLLA_ANSIBLE=0
+GEN_SCRIPT=0
 
-while [ "$#" -gt 0 ]; do
+if [ "$#" -le 1 ]; then
+    usage
+    exit 0
+fi
+
+while [ "$#" -gt 1 ]; do
     case "$1" in
 
     (--repo-port|-r)
@@ -119,6 +136,40 @@ while [ "$#" -gt 0 ]; do
     (--bind-addr|-a)
             BIND_ADDR="$2"
             shift 2
+            ;;
+
+    (--install-docker|-i)
+            INSTALL_DOCKER=1
+            shift 1
+            ;;
+
+    (--setup-repo|-s)
+            SETUP_REPO=1
+            shift 1
+            ;;
+
+    (--install-kolla-ansible|-t)
+            INSTALL_KOLLA_ANSIBLE=1
+            shift 1
+            ;;
+
+    (--config-kolla-ansible|-c)
+            CONFIG_KOLLA_ANSIBLE=1
+            shift 1
+            ;;
+
+    (--gen-script|-g)
+            GEN_SCRIPT=1
+            shift 1
+            ;;
+
+    (--install-all|-all)
+            INSTALL_DOCKER=1
+            SETUP_REPO=1
+            INSTALL_KOLLA_ANSIBLE=1
+            CONFIG_KOLLA_ANSIBLE=1
+            GEN_SCRIPT=1
+            shift 1
             ;;
 
     (--help|-h)
@@ -157,140 +208,156 @@ fi
 
 
 # Install docker-ce on the deployment-server
-section "Install docker-ce and check docker daemon"
-dpkg -i ${CE_BASE}/OpenStackCE/docker-ce/*.deb 1>/dev/null
-check_status $? "Install docker-ce"
+if [ ${INSTALL_DOCKER} -eq 1 ]; then
+    section "Install docker-ce and check docker daemon"
+    dpkg -i ${CE_BASE}/OpenStackCE/docker-ce/*.deb 1>/dev/null
+    check_status $? "Install docker-ce"
 
-status=`systemctl status docker -q --no-pager | grep "Active: active (running)"`
-rc=$(if [[ -z "$status" ]]; then echo 1;else echo 0;fi)
-check_status $rc "Start docker service"
-
-
-# Load docker images used to run local repo and local pypiserver
-section "Load docker images used to run local repo, pypiserver and docker registry"
-docker load -i "${CE_BASE}/OpenStackCE/deployment-docker-images.tar" 1>/dev/null
-check_status $? "Load docker image"
+    status=`systemctl status docker -q --no-pager | grep "Active: active (running)"`
+    rc=$(if [[ -z "$status" ]]; then echo 1;else echo 0;fi)
+    check_status $rc "Start docker service"
 
 
-# Check the list contains all the required docker images
-image_list=($REPO_SERVER_IMG $DOCKER_REGISTRY_IMG $PYPI_SERVER_IMG)
-missing_image=""
-for i in ${image_list[@]}; do
-    output=$(docker images --format "{{.Repository}}:{{.Tag}}" $i)
-    if [[ "$output" != "$i" ]]; then
-        missing_image=${missing_image}" "$i
+    # Load docker images used to run local repo and local pypiserver
+    section "Load docker images used to run local repo, pypiserver and docker registry"
+    docker load -i "${CE_BASE}/OpenStackCE/deployment-docker-images.tar" 1>/dev/null
+    check_status $? "Load docker image"
+
+
+    # Check the list contains all the required docker images
+    image_list=($REPO_SERVER_IMG $DOCKER_REGISTRY_IMG $PYPI_SERVER_IMG)
+    missing_image=""
+    for i in ${image_list[@]}; do
+        output=$(docker images --format "{{.Repository}}:{{.Tag}}" $i)
+        if [[ "$output" != "$i" ]]; then
+            missing_image=${missing_image}" "$i
+        fi
+    done
+    if [[ ${missing_image} != "" ]]; then
+        echo "Docker image: ${missing_image} not found."
+        echo "Aborting."
+        exit 1
     fi
-done
-if [[ ${missing_image} != "" ]]; then
-    echo "Docker image: ${missing_image} not found."
-    echo "Aborting."
-    exit 1
+
+
+    section "Stop and Remove existed CE repo containers"
+    echo "Finding containers to kill..."
+    containers_to_kill=$(find_containers_to_kill)
+    if [ "${containers_to_kill}" != "" ]; then
+        echo "Containers to kill: ${containers_to_kill}"
+        echo "Stopping containers..."
+        (docker stop -t 5 ${containers_to_kill} 2>&1) > /dev/null
+        echo "Removing containers..."
+        (docker rm -f ${containers_to_kill} 2>&1) > /dev/null
+    else
+        echo "No existed CE related containers Found."
+    fi
+
+
+    section "Start local package repository server"
+    docker run -d --name $REPO_SERVER --restart=always -v ${CE_BASE}/OpenStackCE/ubuntu-mirror:/usr/share/nginx/html:ro -p ${REPOSITORY_PORT}:80 $REPO_SERVER_IMG 1>/dev/null
+    check_status $?
+
+
+    section "Start local docker registry server"
+    docker run -d --name $DOCKER_REGISTRY --restart=always -v ${CE_BASE}/OpenStackCE/docker-registry:/var/lib/registry -p ${DOCKER_REGISTRY_PORT}:5000 $DOCKER_REGISTRY_IMG 1>/dev/null
+    check_status $?
+
+
+    section "Start local PYPI server"
+    docker run -d --name $PYPI_SERVER --restart=always -v ${CE_BASE}/OpenStackCE/pypi:/data/packages -p ${PYPI_PORT}:8080 $PYPI_SERVER_IMG 1>/dev/null
+    check_status $?
 fi
 
+if [ $SETUP_REPO -eq 1 ]; then
+    section "Generate bootstrap files including sources.list and pip.conf"
+    mkdir -p ${CE_BASE}/OpenStackCE/bootstrap_files
+    cp -f ${CE_BASE}/OpenStackCE/kolla-ansible/tools/deployer_for_linuxone/templates/ubuntu/* ${CE_BASE}/OpenStackCE/bootstrap_files/
+    check_status $? "Copy sources.list templates"
+    server_ip=$(get_bind_addr)
+    if [[ $? -ne 0 ]]; then
+        echo "Error: get_bind_addr failed!"
+        exit -1
+    fi
+    echo "Get server bind address: $server_ip"
+    sed -i "s/SERVER:REPO_PORT/${server_ip}:${REPOSITORY_PORT}/g" ${CE_BASE}/OpenStackCE/bootstrap_files/*list*
+    sed -i "s/SERVER/${server_ip}/g" ${CE_BASE}/OpenStackCE/bootstrap_files/pip.conf
+    sed -i "s/PORT/${PYPI_PORT}/g" ${CE_BASE}/OpenStackCE/bootstrap_files/pip.conf
 
-section "Stop and Remove existed CE repo containers"
-echo "Finding containers to kill..."
-containers_to_kill=$(find_containers_to_kill)
-if [ "${containers_to_kill}" != "" ]; then
-    echo "Containers to kill: ${containers_to_kill}"
-    echo "Stopping containers..."
-    (docker stop -t 5 ${containers_to_kill} 2>&1) > /dev/null
-    echo "Removing containers..."
-    (docker rm -f ${containers_to_kill} 2>&1) > /dev/null
-else
-    echo "No existed CE related containers Found."
+
+    section "Setup deployment server to use local package repository and PYPI server"
+    suffix=`date +%Y%m%d`
+    cp -f /etc/apt/sources.list /etc/apt/sources.list.bk${suffix}
+    check_status $? "Backup the old /etc/apt/sources.list"
+    cp -f ${CE_BASE}/OpenStackCE/bootstrap_files/sources.list.x86 /etc/apt/sources.list
+    check_status $? "Setup /etc/apt/sources.list"
+    apt-get update 1>/dev/null
+    check_status $? "Check repo with apt-get update command"
+    mkdir -p ${HOME}/.pip
+    cp -f ${CE_BASE}/OpenStackCE/bootstrap_files/pip.conf ${HOME}/.pip/pip.conf
+    check_status $? "Setup ${HOME}/.pip/pip.conf"
+
+
+    section "Install git and pip from local repository"
+    apt-get install -y git python-pip 1>/dev/null
+    check_status $?
+
+
+    section "Upgrade pip to latest"
+    pip install pip==9.0.3 1>/dev/null
+    check_status $? "Install pip of version 9.0.3 firstly"
+    export PATH=$PATH && pip install --upgrade pip 1>/dev/null
+    check_status $? "Upgrade pip to latest version"
+    export PATH=$PATH && pip list 1>/dev/null
+    check_status $? "Check pip list can work after upgrade"
 fi
 
-
-section "Start local package repository server"
-docker run -d --name $REPO_SERVER --restart=always -v ${CE_BASE}/OpenStackCE/ubuntu-mirror:/usr/share/nginx/html:ro -p ${REPOSITORY_PORT}:80 $REPO_SERVER_IMG 1>/dev/null
-check_status $?
-
-
-section "Start local docker registry server"
-docker run -d --name $DOCKER_REGISTRY --restart=always -v ${CE_BASE}/OpenStackCE/docker-registry:/var/lib/registry -p ${DOCKER_REGISTRY_PORT}:5000 $DOCKER_REGISTRY_IMG 1>/dev/null
-check_status $?
-
-
-section "Start local PYPI server"
-docker run -d --name $PYPI_SERVER --restart=always -v ${CE_BASE}/OpenStackCE/pypi:/data/packages -p ${PYPI_PORT}:8080 $PYPI_SERVER_IMG 1>/dev/null
-check_status $?
-
-
-section "Generate bootstrap files including sources.list and pip.conf"
-mkdir -p ${CE_BASE}/OpenStackCE/bootstrap_files
-cp -f ${CE_BASE}/OpenStackCE/kolla-ansible/tools/deployer_for_linuxone/templates/ubuntu/* ${CE_BASE}/OpenStackCE/bootstrap_files/
-check_status $? "Copy sources.list templates"
-server_ip=$(get_bind_addr)
-if [[ $? -ne 0 ]]; then
-    echo "Error: get_bind_addr failed!"
-    exit -1
-fi
-echo "Get server bind address: $server_ip"
-sed -i "s/SERVER:REPO_PORT/${server_ip}:${REPOSITORY_PORT}/g" ${CE_BASE}/OpenStackCE/bootstrap_files/*list*
-sed -i "s/SERVER/${server_ip}/g" ${CE_BASE}/OpenStackCE/bootstrap_files/pip.conf
-sed -i "s/PORT/${PYPI_PORT}/g" ${CE_BASE}/OpenStackCE/bootstrap_files/pip.conf
-
-
-section "Setup deployment server to use local package repository and PYPI server"
-suffix=`date +%Y%m%d`
-cp -f /etc/apt/sources.list /etc/apt/sources.list.bk${suffix}
-check_status $? "Backup the old /etc/apt/sources.list"
-cp -f ${CE_BASE}/OpenStackCE/bootstrap_files/sources.list.x86 /etc/apt/sources.list
-check_status $? "Setup /etc/apt/sources.list"
-apt-get update 1>/dev/null
-check_status $? "Check repo with apt-get update command"
-mkdir -p ${HOME}/.pip
-cp -f ${CE_BASE}/OpenStackCE/bootstrap_files/pip.conf ${HOME}/.pip/pip.conf
-check_status $? "Setup ${HOME}/.pip/pip.conf"
-
-
-section "Install git and pip from local repository"
-apt-get install -y git python-pip 1>/dev/null
-check_status $?
-
-
-section "Upgrade pip to latest"
-pip install pip==9.0.3 1>/dev/null
-check_status $? "Install pip of version 9.0.3 firstly"
-export PATH=$PATH && pip install --upgrade pip 1>/dev/null
-check_status $? "Upgrade pip to latest version"
-export PATH=$PATH && pip list 1>/dev/null
-check_status $? "Check pip list can work after upgrade"
-
-
-section "Install kolla-ansible on deployment server"
-apt-get install -y python-dev libffi-dev gcc libssl-dev python-selinux python-setuptools ansible 1>/dev/null
-check_status $? "Install depended packages and ansible"
-pip install -U ansible 1>/dev/null
-check_status $? "Upgrade ansible"
-tee /etc/ansible/ansible.cfg 1>/dev/null << EOF
+if [ $INSTALL_KOLLA_ANSIBLE -eq 1 ]; then
+    section "Install kolla-ansible on deployment server"
+    apt-get install -y python-dev libffi-dev gcc libssl-dev python-selinux python-setuptools ansible 1>/dev/null
+    check_status $? "Install depended packages and ansible"
+    pip install -U ansible 1>/dev/null
+    check_status $? "Upgrade ansible"
+    tee /etc/ansible/ansible.cfg 1>/dev/null << EOF
 [defaults]
 host_key_checking=False
 pipelining=True
 forks=100
 EOF
-check_status $? "Update ansible configuration file"
-apt-get remove -y python-yaml 1>/dev/null
-pip install PyYAML 1>/dev/null
-check_status $? "Remove python-yaml and reinstall with pip"
-pip install ansible 1>/dev/null
-check_status $? "Reinstall ansible with pip"
-current_dir=$(pwd) && cd ${CE_BASE}/OpenStackCE/kolla-ansible/ && pip install . 1>/dev/null && rc=$? && cd ${current_dir}
-check_status $rc "Install kolla-ansible"
+    check_status $? "Update ansible configuration file"
+    apt-get remove -y python-yaml 1>/dev/null
+    pip install PyYAML 1>/dev/null
+    check_status $? "Remove python-yaml and reinstall with pip"
+    pip install ansible 1>/dev/null
+    check_status $? "Reinstall ansible with pip"
+    current_dir=$(pwd) && cd ${CE_BASE}/OpenStackCE/kolla-ansible/ && pip install . 1>/dev/null && rc=$? && cd ${current_dir}
+    check_status $rc "Install kolla-ansible"
 
 
-section "COPY configuration files to /etc/kolla"
-suffix=`date +%Y%m%d`
-cp -rf /etc/kolla /etc/kolla.bk${suffix} 2>/dev/null
-rm -rf /etc/kolla 2>/dev/null
-check_status $? "Backup old /etc/kolla if exists"
-cp -rf ${CE_BASE}/OpenStackCE/kolla-ansible/etc/kolla /etc/
-check_status $? "Copy /etc/kolla files"
-cp ${CE_BASE}/OpenStackCE/kolla-ansible/ansible/inventory/* /etc/kolla/
-check_status $? "Copy inventory files to /etc/kolla/"
-mkdir -p /etc/kolla/config/nova
-tee /etc/kolla/config/nova/nova-compute.conf 1>/dev/null << EOF
+    section "Update globals.yml with the local repo info"
+    sed -i "s/LOCAL_DOCKER_REGISTRY/${server_ip}:${DOCKER_REGISTRY_PORT}/g" /etc/kolla/globals.yml
+    check_status $? "Update docker registry info"
+    sed -i "s/LOCAL_APT_REPO/${server_ip}:${REPOSITORY_PORT}/g" /etc/kolla/globals.yml
+    check_status $? "Update apt package repo info"
+
+
+    section "Install sshpass from local repository"
+    apt-get install -y sshpass 1>/dev/null
+    check_status $?
+fi
+
+if [ $CONFIG_KOLLA_ANSIBLE -eq 1 ]; then
+    section "COPY configuration files to /etc/kolla"
+    suffix=`date +%Y%m%d`
+    cp -rf /etc/kolla /etc/kolla.bk${suffix} 2>/dev/null
+    rm -rf /etc/kolla 2>/dev/null
+    check_status $? "Backup old /etc/kolla if exists"
+    cp -rf ${CE_BASE}/OpenStackCE/kolla-ansible/etc/kolla /etc/
+    check_status $? "Copy /etc/kolla files"
+    cp ${CE_BASE}/OpenStackCE/kolla-ansible/ansible/inventory/* /etc/kolla/
+    check_status $? "Copy inventory files to /etc/kolla/"
+    mkdir -p /etc/kolla/config/nova
+    tee /etc/kolla/config/nova/nova-compute.conf 1>/dev/null << EOF
 [DEFAULT]
 enable_apis=osapi_compute,metadata
 compute_driver=libvirt.LibvirtDriver
@@ -305,19 +372,15 @@ virt_type=kvm
 cpu_mode=none
 inject_partition=-2
 EOF
-check_status $? "Add nova-compute.conf into /etc/kolla/config/nova/"
+    check_status $? "Add nova-compute.conf into /etc/kolla/config/nova/"
+fi
 
-
-section "Install sshpass from local repository"
-apt-get install -y sshpass 1>/dev/null
-check_status $?
-
-
-section "Generat Script used to setup target nodes to use local repository"
-sources_x86=$(cat ${CE_BASE}/OpenStackCE/bootstrap_files/sources.list.x86)
-sources_s390x=$(cat ${CE_BASE}/OpenStackCE/bootstrap_files/sources.list.s390x)
-pip_conf=$(cat ${CE_BASE}/OpenStackCE/bootstrap_files/pip.conf)
-tee /etc/kolla/openstack-ce-presetups.sh 1>/dev/null << EOF
+if [ $GEN_SCRIPT -eq 1 ]; then
+    section "Generat Script used to setup target nodes to use local repository"
+    sources_x86=$(cat ${CE_BASE}/OpenStackCE/bootstrap_files/sources.list.x86)
+    sources_s390x=$(cat ${CE_BASE}/OpenStackCE/bootstrap_files/sources.list.s390x)
+    pip_conf=$(cat ${CE_BASE}/OpenStackCE/bootstrap_files/pip.conf)
+    tee /etc/kolla/openstack-ce-presetups.sh 1>/dev/null << EOF
 #!/bin/bash
 cp -f /etc/apt/sources.list /etc/apt/sources.list.bk
 node_arch=\$(arch)
@@ -332,16 +395,9 @@ echo "Setup pip.conf"
 mkdir -p \${HOME}/.pip/
 echo "${pip_conf}" > \${HOME}/.pip/pip.conf
 EOF
-chmod +x /etc/kolla/openstack-ce-presetups.sh
-check_status $?
-
-
-section "Update globals.yml with the local repo info"
-sed -i "s/LOCAL_DOCKER_REGISTRY/${server_ip}:${DOCKER_REGISTRY_PORT}/g" /etc/kolla/globals.yml
-check_status $? "Update docker registry info"
-sed -i "s/LOCAL_APT_REPO/${server_ip}:${REPOSITORY_PORT}/g" /etc/kolla/globals.yml
-check_status $? "Update apt package repo info"
-
+    chmod +x /etc/kolla/openstack-ce-presetups.sh
+    check_status $?
+fi
 
 echo ""
 echo "*********************************"
